name: GHCR — Cleanup old versions

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Clean up old and untagged GHCR versions
        uses: dataaxiom/ghcr-cleanup-action@d52806a0dc70b430571a37da1fde39733ffd640f  # v1
        with:
          package: secopstm
          exclude-tags: 'latest,1.1.1a20'
          delete-untagged: true
          delete-ghost-images: true
